export const GLOBAL_ATTRIBUTES = new Set([
  // https://html.spec.whatwg.org/multipage/dom.html#global-attributes
  "accesskey",
  "autocapitalize",
  "autofocus",
  "contenteditable",
  "dir",
  "draggable",
  "enterkeyhint",
  "hidden",
  "inputmode",
  "is",
  "itemid",
  "itemprop",
  "itemref",
  "itemscope",
  "itemtype",
  "lang",
  "nonce",
  "spellcheck",
  "style",
  "tabindex",
  "title",
  "translate",
]);

export const VALID_PROPS_RULES = {
  // https://html.spec.whatwg.org/multipage/input.html#input-type-attr-summary
  HTMLInputElement: {
    "[type=hidden]": new Set(["autocomplete", "value"]),
    "[type=text]": new Set([
      "autocomplete",
      "dirname",
      "list",
      "maxlength",
      "minlength",
      "pattern",
      "placeholder",
      "readonly",
      "required",
      "size",
      "value",
      "list",
      "selectionstart",
      "selectionend",
      "selectiondirection",
    ]),
    "[type=search]": new Set([
      "autocomplete",
      "dirname",
      "list",
      "maxlength",
      "minlength",
      "pattern",
      "placeholder",
      "readonly",
      "required",
      "size",
      "value",
      "list",
      "selectionstart",
      "selectionend",
      "selectiondirection",
    ]),
    "[type=url]": new Set([
      "autocomplete",
      "list",
      "maxlength",
      "minlength",
      "pattern",
      "placeholder",
      "readonly",
      "required",
      "size",
      "value",
      "list",
      "selectionstart",
      "selectionend",
      "selectiondirection",
    ]),
    "[type=tel]": new Set([
      "autocomplete",
      "list",
      "maxlength",
      "minlength",
      "pattern",
      "placeholder",
      "readonly",
      "required",
      "size",
      "value",
      "list",
      "selectionstart",
      "selectionend",
      "selectiondirection",
    ]),
    "[type=email]": new Set([
      "autocomplete",
      "list",
      "maxlength",
      "minlength",
      "multiple",
      "pattern",
      "placeholder",
      "readonly",
      "required",
      "size",
      "value",
      "list",
    ]),
    "[type=password]": new Set([
      "autocomplete",
      "maxlength",
      "minlength",
      "pattern",
      "placeholder",
      "readonly",
      "required",
      "size",
      "value",
      "selectionstart",
      "selectionend",
      "selectiondirection",
    ]),
    "[type=date]": new Set([
      "autocomplete",
      "list",
      "max",
      "min",
      "readonly",
      "required",
      "step",
      "value",
      "valueasdate",
      "valueasnumber",
      "list",
    ]),
    "[type=month]": new Set([
      "autocomplete",
      "list",
      "max",
      "min",
      "readonly",
      "required",
      "step",
      "value",
      "valueasdate",
      "valueasnumber",
      "list",
    ]),
    "[type=week]": new Set([
      "autocomplete",
      "list",
      "max",
      "min",
      "readonly",
      "required",
      "step",
      "value",
      "valueasdate",
      "valueasnumber",
      "list",
    ]),
    "[type=time]": new Set([
      "autocomplete",
      "list",
      "max",
      "min",
      "readonly",
      "required",
      "step",
      "value",
      "valueasdate",
      "valueasnumber",
      "list",
    ]),
    "[type=datetime-local]": new Set([
      "autocomplete",
      "list",
      "max",
      "min",
      "readonly",
      "required",
      "step",
      "value",
      "valueasnumber",
      "list",
    ]),
    "[type=number]": new Set([
      "autocomplete",
      "list",
      "max",
      "min",
      "placeholder",
      "readonly",
      "required",
      "step",
      "value",
      "valueasnumber",
      "list",
    ]),
    "[type=range]": new Set([
      "autocomplete",
      "list",
      "max",
      "min",
      "step",
      "value",
      "valueasnumber",
      "list",
    ]),
    "[type=color]": new Set(["autocomplete", "list", "value"]),
    "[type=checkbox]": new Set(["checked", "required", "checked", "value"]),
    "[type=radio]": new Set(["checked", "required", "checked", "value"]),
    "[type=file]": new Set(["accept", "multiple", "required", "files", "value"]),
    "[type=submit]": new Set([
      "formaction",
      "formenctype",
      "formmethod",
      "formnovalidate",
      "formtarget",
      "value",
    ]),
    "[type=image]": new Set([
      "alt",
      "formaction",
      "formenctype",
      "formmethod",
      "formnovalidate",
      "formtarget",
      "height",
      "src",
      "width",
      "value",
    ]),
    "[type=reset]": new Set(["value"]),
    "[type=button]": new Set(["value"]),
  },
};
